### ISSUE TITLE
--remote-wait doesn't end wait when opened buffer is closed

### ISSUE THREAD

**Issue by macinjosh** [mhinz/neovim-remote#19]
In my terminal I have my `$EDITOR` environment variable set to:

`nvr --servername /tmp/nvim.socket --remote-wait`

Neovim correctly waits however I have to completely `:quit` neovim for nvr to stop waiting. To correctly mirror vim's behavior nvr should stop waiting when the opened buffer is closed not when neovim is closed.

**Comment by mhinz** [comment]
Oh, that would be quite hacky.

Assuming `nvr --remote-wait file1 file2`, when should it return?

**Comment by macinjosh** [comment]
I would assume when all files passed with the wait command have their buffers closed.

**Comment by mhinz** [comment]
Naive approach:

For each file that nvr attempts to open it will also have to add a buffer-local autocmd that decrements some kind of global counter if that buffers gets deleted.

Let's see if it works out what way.

**Comment by mhinz** [comment]
Argh, I'm an idiot. The functionality is already there.

Can you test if it works as expected with `NVIM_TERMINAL=1 nvr --remote-wait file1 file2`?

**Comment by mhinz** [comment]
I also released v1.3.0. A `pip3 install -U neovim-remote` should do it.

**Comment by macinjosh** [comment]
@mhinz Thanks a ton, I appreciate your work on this project! I'll give that a shot soon, work has got me busy for the rest of the day..

**Comment by mhinz** [comment]
No problem. :-)

**Comment by mhinz** [comment]
It does work. ;-)

**Comment by R3load** [comment]
The bug is back for me, can reproduce with each of the `*wait*` options:

* `--remote-wait`
* `--remote-wait-silent`
* `--remote-tab-wait`
* `--remote-tab-wait-silent`

Doesn't even twitch on `BufDelete`, instead waits for nvim to exit completely.
Exactly as described by the OP.
Vim, on the other hand, works as expected when trying to reproduce the bug (same commandlines, replace `nvr` with `vim`)

`pacman -Q neovim-remote-git`:
> neovim-remote-git 1.6.1.r0.g53ce66c-1

`nvim --version`:
> NVIM v0.2.1-339-gf8e3bc63e
> Build type: RelWithDebInfo
> Compilation: /usr/lib/hardening-wrapper/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/rld/abs/neovim-git/src/neovim-git/build/config -I/home/rld/abs/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/rld/abs/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/rld/abs/neovim-git/src/neovim-git/build/include
> Compiled by rld@palantir
> 
> Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
> For differences from Vim, see :help vim-differences
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"


`uname -a`:
> Linux palantir 4.11.4-1-ARCH #1 SMP PREEMPT Fri Jun 9 07:46:48 CEST 2017 x86_64 GNU/Linux

**Comment by mhinz** [comment]
The functionality relies on the buffer getting deleted.

`:wq` and `ZZ` don't delete the buffer, they save/update and quit the current window.

`:bd` deletes the buffer.
